In [5]:
import os
import pandas as pd
import numpy as np
import torch

In [6]:
os.makedirs(os.path.join("..","data"),exist_ok=True)
data_file = os.path.join("..","data","house_tiny.csv")
with open(data_file, "w") as f:
    f.write("NumRooms,Alley,Price\n")
    f.write("NA,Pave,127500\n")
    f.write("2,NA,106000\n")
    f.write("4,NA,178100\n")
    f.write("NA,NA,140000\n")

In [10]:
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [14]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:,2]

In [15]:
print(inputs)

   NumRooms Alley
0       NaN  Pave
1       2.0   NaN
2       4.0   NaN
3       NaN   NaN


In [16]:
inputs = inputs.fillna(inputs.mean())

/var/folders/pj/dxyjgfn97b5g1hcy442ww_sh0000gn/T/ipykernel_16508/64727764.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  inputs = inputs.fillna(inputs.mean())


In [19]:
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [23]:
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [24]:
X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

In [25]:
x = torch.arange(4)

In [26]:
x

tensor([0, 1, 2, 3])

In [27]:
x[3]

tensor(3)

In [28]:
len(x)

4

In [29]:
x.shape

torch.Size([4])

In [30]:
A = torch.arange(20).reshape(5,4)

In [31]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [32]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [36]:
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [37]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
B = A.clone()

In [40]:
A+B

tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])

In [41]:
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [44]:
a = 2
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [45]:
a + X

tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])

In [47]:
a*X

tensor([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]],

        [[24, 26, 28, 30],
         [32, 34, 36, 38],
         [40, 42, 44, 46]]])

In [52]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [50]:
A.shape

torch.Size([5, 4])

In [49]:
A.sum()

tensor(190.)

In [51]:
A.sum(axis=0)

tensor([40., 45., 50., 55.])

In [53]:
A.numel()

20

In [54]:
A.shape

torch.Size([5, 4])

In [57]:
A.mean(axis=0)

tensor([ 8.,  9., 10., 11.])

In [58]:
sum_A = A.sum(axis=1, keepdims=True) # keep dimensions

In [59]:
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [60]:
A.sum(axis=1)

tensor([ 6., 22., 38., 54., 70.])

In [61]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [63]:
A.cumsum(axis=0) #累加 按照行累加

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [64]:
y = torch.ones(4,dtype = torch.float32)

In [73]:
x = torch.arange(4,dtype = torch.float32)

In [76]:
x,y, torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [77]:
torch.sum(x*y)

tensor(6.)

In [78]:
A.shape,x.shape,torch.mv(A,x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [79]:
B = torch.ones(4,3)
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [80]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)#2-norm

tensor(5.)

In [82]:
torch.abs(u).sum()#1-norm

tensor(7.)

In [83]:
torch.norm(torch.ones((4,9)))

tensor(6.)