In [12]:
import torch
#求y=2*x*x 关于x的导数
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [13]:
x.requires_grad_(True)#储存梯度值

tensor([0., 1., 2., 3.], requires_grad=True)

In [14]:
x.grad

In [15]:
x=torch.arange(4.0,requires_grad=True)

In [16]:
x.grad

In [17]:
y = 2*torch.dot(x,x)

In [18]:
y

tensor(28., grad_fn=<MulBackward0>)

In [19]:
y.backward()

In [20]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [21]:
x.grad == 4*x

tensor([True, True, True, True])

In [23]:
x.grad.zero_()
y = x.sum()


In [25]:
y

tensor(6., grad_fn=<SumBackward0>)

In [24]:
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [26]:
x

tensor([0., 1., 2., 3.], requires_grad=True)